### PR TITLE
Use AFE to replicate van Dorp Schuitman model

### PR DESCRIPTION
**Pull request by hagenw**
This tries to implement the model described in [1] by using the AFE.

The model is currently implemented as the function `afeRAA()` under `test/Development_test_scripts/`.

[1] van Dorp Schuitman, J., de Vries, D., & Lindau, A. (2013), "Deriving content-specific measures of room acoustic perception using  a binaural, nonlinear auditory model," The Journal of the Acoustical Society of America, 133(March), 1572–1585.

### CODE REVIEW

**Comment by hagenw** [comment]
@ryanckim: besides adding new functions for the van Dorp Schuitmann model you also changed the adaptation processor `adaptationProc()`.
Could you shortly describe what you changed there and if this can have an influence on other parts of the AFE?

**Comment by Hardcorehobel** [comment]
It seems that the room acoustic analyzer (RAA) is a standalone program placed in test\afeRAA. If this function is supposed to be used, I would rather place it in tools and provide a simple demo script, even if that demo is only loading a file and calling afeRAA directly. Otherwise, the visibility of this function is so low that it may not be used at all. What do you think @ryanckim @hagenw ?

**Comment by hagenw** [comment]
That sounds good. The original idea was to implement it as a processor, but there was not enough time, so it was implemented as a separate function. But I agree, that it is not only a test function and we should move it to a more prominent place. `tools` would be fine with me.

**Comment by Hardcorehobel** [comment]
ok, who's going to do it?

**Comment by hagenw** [comment]
I will do it.

**Comment by Hardcorehobel** [comment]
Cool, do you mind creating a little DEMO_RAA, which essentially loads a speech signal and triggers afeRAA?

**Pull request merged**
